// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PruebasBBD.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class IntegracionCRUDDeCategoriasFeature : object, Xunit.IClassFixture<IntegracionCRUDDeCategoriasFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Integracion CRUD de Categorias", "  Como sistema de gestion\r\n  Quiero poder crear leer actualizar y eliminar catego" +
                "rias\r\n  Para mantener organizado el inventario", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CategoryIntegration.feature"
#line hidden
        
        public IntegracionCRUDDeCategoriasFeature(IntegracionCRUDDeCategoriasFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
  await testRunner.GivenAsync("la base de datos esta limpia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CA-01 - Crear categoria basica - Happy Path 1")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Categorias")]
        [Xunit.TraitAttribute("Description", "CA-01 - Crear categoria basica - Happy Path 1")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "category")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CA_01_CrearCategoriaBasica_HappyPath1()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "category",
                    "create",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CA-01 - Crear categoria basica - Happy Path 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table1.AddRow(new string[] {
                            "Name",
                            "Lacteos"});
                table1.AddRow(new string[] {
                            "Description",
                            "Productos lacteos frescos"});
#line 15
  await testRunner.WhenAsync("creo una categoria con los siguientes datos:", ((string)(null)), table1, "When ");
#line hidden
#line 19
  await testRunner.ThenAsync("la categoria debe crearse exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
  await testRunner.AndAsync("el nombre debe ser \"Lacteos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
  await testRunner.AndAsync("el Status debe ser 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CA-02 - Crear categoria con descripcion larga - Happy Path 2")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Categorias")]
        [Xunit.TraitAttribute("Description", "CA-02 - Crear categoria con descripcion larga - Happy Path 2")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "category")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CA_02_CrearCategoriaConDescripcionLarga_HappyPath2()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "category",
                    "create",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CA-02 - Crear categoria con descripcion larga - Happy Path 2", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table2.AddRow(new string[] {
                            "Name",
                            "Bebidas"});
                table2.AddRow(new string[] {
                            "Description",
                            "Bebidas alcoholicas no alcoholicas jugos y refrescos"});
#line 25
  await testRunner.WhenAsync("creo una categoria con los siguientes datos:", ((string)(null)), table2, "When ");
#line hidden
#line 29
  await testRunner.ThenAsync("la categoria debe crearse exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
  await testRunner.AndAsync("el nombre debe ser \"Bebidas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
  await testRunner.AndAsync("el Status debe ser 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CA-03 - Crear categoria sin nombre - Unhappy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Categorias")]
        [Xunit.TraitAttribute("Description", "CA-03 - Crear categoria sin nombre - Unhappy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "category")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "unhappy")]
        public async System.Threading.Tasks.Task CA_03_CrearCategoriaSinNombre_UnhappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "category",
                    "create",
                    "unhappy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CA-03 - Crear categoria sin nombre - Unhappy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table3.AddRow(new string[] {
                            "Name",
                            ""});
                table3.AddRow(new string[] {
                            "Description",
                            "Descripcion sin nombre"});
#line 35
  await testRunner.WhenAsync("creo una categoria con los siguientes datos:", ((string)(null)), table3, "When ");
#line hidden
#line 39
  await testRunner.ThenAsync("la creacion debe fallar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CA-04 - Actualizar categoria exitosamente - Happy Path 1")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Categorias")]
        [Xunit.TraitAttribute("Description", "CA-04 - Actualizar categoria exitosamente - Happy Path 1")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "category")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CA_04_ActualizarCategoriaExitosamente_HappyPath1()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "category",
                    "update",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CA-04 - Actualizar categoria exitosamente - Happy Path 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 47
  await testRunner.GivenAsync("existe una categoria con nombre \"Lacteos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table4.AddRow(new string[] {
                            "Name",
                            "Productos Lacteos"});
                table4.AddRow(new string[] {
                            "Description",
                            "Leche queso yogurt y derivados lacteos"});
#line 48
  await testRunner.WhenAsync("actualizo la categoria con:", ((string)(null)), table4, "When ");
#line hidden
#line 52
  await testRunner.ThenAsync("la actualizacion debe ser exitosa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 53
  await testRunner.AndAsync("los datos deben reflejarse en la base de datos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CA-05 - Actualizar manteniendo mismo nombre - Happy Path 2")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Categorias")]
        [Xunit.TraitAttribute("Description", "CA-05 - Actualizar manteniendo mismo nombre - Happy Path 2")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "category")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CA_05_ActualizarManteniendoMismoNombre_HappyPath2()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "category",
                    "update",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CA-05 - Actualizar manteniendo mismo nombre - Happy Path 2", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 57
  await testRunner.GivenAsync("existe una categoria con nombre \"Bebidas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table5.AddRow(new string[] {
                            "Name",
                            "Bebidas"});
                table5.AddRow(new string[] {
                            "Description",
                            "Bebidas varias actualizadas"});
#line 58
  await testRunner.WhenAsync("actualizo la categoria con:", ((string)(null)), table5, "When ");
#line hidden
#line 62
  await testRunner.ThenAsync("la actualizacion debe ser exitosa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CA-06 - Actualizar con nombre duplicado - Unhappy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Categorias")]
        [Xunit.TraitAttribute("Description", "CA-06 - Actualizar con nombre duplicado - Unhappy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "category")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "unhappy")]
        public async System.Threading.Tasks.Task CA_06_ActualizarConNombreDuplicado_UnhappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "category",
                    "update",
                    "unhappy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CA-06 - Actualizar con nombre duplicado - Unhappy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Description"});
                table6.AddRow(new string[] {
                            "Lacteos",
                            "Productos"});
                table6.AddRow(new string[] {
                            "Bebidas",
                            "Liquidos"});
#line 66
  await testRunner.GivenAsync("existen las siguientes categorias:", ((string)(null)), table6, "Given ");
#line hidden
#line 70
  await testRunner.WhenAsync("intento actualizar \"Bebidas\" con nombre \"Lacteos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
  await testRunner.ThenAsync("la actualizacion debe fallar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CA-07 - Eliminar categoria - Happy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Categorias")]
        [Xunit.TraitAttribute("Description", "CA-07 - Eliminar categoria - Happy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "category")]
        [Xunit.TraitAttribute("Category", "delete")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CA_07_EliminarCategoria_HappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "category",
                    "delete",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CA-07 - Eliminar categoria - Happy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 79
  await testRunner.GivenAsync("existe una categoria con nombre \"Temporal\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
  await testRunner.WhenAsync("elimino la categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
  await testRunner.ThenAsync("el Status de la categoria debe cambiar a 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
  await testRunner.AndAsync("la categoria no debe aparecer en busquedas activas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CA-08 - Listar categorias activas - Happy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Categorias")]
        [Xunit.TraitAttribute("Description", "CA-08 - Listar categorias activas - Happy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "category")]
        [Xunit.TraitAttribute("Category", "read")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CA_08_ListarCategoriasActivas_HappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "category",
                    "read",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CA-08 - Listar categorias activas - Happy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 89
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Description",
                            "Status"});
                table7.AddRow(new string[] {
                            "Activa1",
                            "Desc1",
                            "1"});
                table7.AddRow(new string[] {
                            "Activa2",
                            "Desc2",
                            "1"});
                table7.AddRow(new string[] {
                            "Inactiva",
                            "Desc3",
                            "0"});
#line 90
  await testRunner.GivenAsync("existen las siguientes categorias:", ((string)(null)), table7, "Given ");
#line hidden
#line 95
  await testRunner.WhenAsync("obtengo todas las categorias", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
  await testRunner.ThenAsync("debo recibir 2 categorias", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 97
  await testRunner.AndAsync("todas deben tener Status 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await IntegracionCRUDDeCategoriasFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await IntegracionCRUDDeCategoriasFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
