// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PruebasBBD.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class IntegracionCRUDDeClientesFeature : object, Xunit.IClassFixture<IntegracionCRUDDeClientesFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Integracion CRUD de Clientes", "  Como sistema de gestion\r\n  Quiero poder crear leer actualizar y eliminar client" +
                "es\r\n  Para gestionar la cartera de clientes", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ClientIntegration.feature"
#line hidden
        
        public IntegracionCRUDDeClientesFeature(IntegracionCRUDDeClientesFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
  await testRunner.GivenAsync("la base de datos esta limpia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CL-01 - Crear cliente completo - Happy Path 1")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Clientes")]
        [Xunit.TraitAttribute("Description", "CL-01 - Crear cliente completo - Happy Path 1")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "client")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CL_01_CrearClienteCompleto_HappyPath1()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "client",
                    "create",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CL-01 - Crear cliente completo - Happy Path 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table8.AddRow(new string[] {
                            "BusinessName",
                            "Juan Perez"});
                table8.AddRow(new string[] {
                            "Email",
                            "juan.perez@example.com"});
                table8.AddRow(new string[] {
                            "TaxDocument",
                            "1234567"});
                table8.AddRow(new string[] {
                            "Address",
                            "Av. Siempre Viva 123"});
#line 15
  await testRunner.WhenAsync("creo un cliente con los siguientes datos:", ((string)(null)), table8, "When ");
#line hidden
#line 21
  await testRunner.ThenAsync("el cliente debe crearse exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
  await testRunner.AndAsync("debe tener Status 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
  await testRunner.AndAsync("el TaxDocument debe ser unico", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CL-02 - Crear cliente sin direccion - Happy Path 2")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Clientes")]
        [Xunit.TraitAttribute("Description", "CL-02 - Crear cliente sin direccion - Happy Path 2")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "client")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CL_02_CrearClienteSinDireccion_HappyPath2()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "client",
                    "create",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CL-02 - Crear cliente sin direccion - Happy Path 2", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table9.AddRow(new string[] {
                            "BusinessName",
                            "Maria Garcia"});
                table9.AddRow(new string[] {
                            "Email",
                            "maria.garcia@example.com"});
                table9.AddRow(new string[] {
                            "TaxDocument",
                            "8765432"});
                table9.AddRow(new string[] {
                            "Address",
                            ""});
#line 27
  await testRunner.WhenAsync("creo un cliente con los siguientes datos:", ((string)(null)), table9, "When ");
#line hidden
#line 33
  await testRunner.ThenAsync("el cliente debe crearse exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
  await testRunner.AndAsync("debe tener Status 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CL-03 - Crear cliente con email invalido - Unhappy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Clientes")]
        [Xunit.TraitAttribute("Description", "CL-03 - Crear cliente con email invalido - Unhappy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "client")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "unhappy")]
        public async System.Threading.Tasks.Task CL_03_CrearClienteConEmailInvalido_UnhappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "client",
                    "create",
                    "unhappy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CL-03 - Crear cliente con email invalido - Unhappy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 38
  await testRunner.WhenAsync("intento crear un cliente con email \"correo_invalido\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
  await testRunner.ThenAsync("la creacion debe fallar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 40
  await testRunner.AndAsync("debe mostrar error de validacion de email", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CL-04 - Actualizar nombre y direccion - Happy Path 1")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Clientes")]
        [Xunit.TraitAttribute("Description", "CL-04 - Actualizar nombre y direccion - Happy Path 1")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "client")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CL_04_ActualizarNombreYDireccion_HappyPath1()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "client",
                    "update",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CL-04 - Actualizar nombre y direccion - Happy Path 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 48
  await testRunner.GivenAsync("existe un cliente con TaxDocument \"1111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table10.AddRow(new string[] {
                            "BusinessName",
                            "Pedro Lopez Actualizado"});
                table10.AddRow(new string[] {
                            "Address",
                            "Nueva Direccion 789"});
#line 49
  await testRunner.WhenAsync("actualizo el cliente con:", ((string)(null)), table10, "When ");
#line hidden
#line 53
  await testRunner.ThenAsync("la actualizacion debe ser exitosa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
  await testRunner.AndAsync("los datos deben estar actualizados en BD", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CL-05 - Actualizar email valido - Happy Path 2")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Clientes")]
        [Xunit.TraitAttribute("Description", "CL-05 - Actualizar email valido - Happy Path 2")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "client")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CL_05_ActualizarEmailValido_HappyPath2()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "client",
                    "update",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CL-05 - Actualizar email valido - Happy Path 2", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 58
  await testRunner.GivenAsync("existe un cliente \"Ana Martinez\" con email \"ana@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
  await testRunner.WhenAsync("actualizo el email a \"ana.martinez@newemail.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
  await testRunner.ThenAsync("la actualizacion debe ser exitosa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 61
  await testRunner.AndAsync("el nuevo email debe ser unico", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CL-06 - Actualizar con TaxDocument duplicado - Unhappy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Clientes")]
        [Xunit.TraitAttribute("Description", "CL-06 - Actualizar con TaxDocument duplicado - Unhappy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "client")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "unhappy")]
        public async System.Threading.Tasks.Task CL_06_ActualizarConTaxDocumentDuplicado_UnhappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "client",
                    "update",
                    "unhappy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CL-06 - Actualizar con TaxDocument duplicado - Unhappy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "BusinessName",
                            "TaxDocument"});
                table11.AddRow(new string[] {
                            "Cliente A",
                            "1111111"});
                table11.AddRow(new string[] {
                            "Cliente B",
                            "2222222"});
#line 65
  await testRunner.GivenAsync("existen los siguientes clientes:", ((string)(null)), table11, "Given ");
#line hidden
#line 69
  await testRunner.WhenAsync("intento actualizar \"Cliente B\" con TaxDocument \"1111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
  await testRunner.ThenAsync("la actualizacion debe fallar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
  await testRunner.AndAsync("debe mostrar error de TaxDocument duplicado", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CL-07 - Eliminar cliente - Happy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Clientes")]
        [Xunit.TraitAttribute("Description", "CL-07 - Eliminar cliente - Happy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "client")]
        [Xunit.TraitAttribute("Category", "delete")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CL_07_EliminarCliente_HappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "client",
                    "delete",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CL-07 - Eliminar cliente - Happy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 79
  await testRunner.GivenAsync("existe un cliente con TaxDocument \"9999999\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
  await testRunner.WhenAsync("elimino el cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
  await testRunner.ThenAsync("el Status del cliente debe cambiar a 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
  await testRunner.AndAsync("el cliente no debe aparecer en busquedas activas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CL-08 - Buscar cliente por TaxDocument - Happy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Clientes")]
        [Xunit.TraitAttribute("Description", "CL-08 - Buscar cliente por TaxDocument - Happy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "client")]
        [Xunit.TraitAttribute("Category", "read")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task CL_08_BuscarClientePorTaxDocument_HappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "client",
                    "read",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CL-08 - Buscar cliente por TaxDocument - Happy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 89
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 90
  await testRunner.GivenAsync("existe un cliente \"Roberto Vargas\" con TaxDocument \"5555555\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
  await testRunner.WhenAsync("busco el cliente por TaxDocument \"5555555\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 92
  await testRunner.ThenAsync("debo recibir los datos del cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 93
  await testRunner.AndAsync("el BusinessName debe ser \"Roberto Vargas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await IntegracionCRUDDeClientesFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await IntegracionCRUDDeClientesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
