// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PruebasBBD.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class IntegracionCRUDDeProductosFeature : object, Xunit.IClassFixture<IntegracionCRUDDeProductosFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Integracion CRUD de Productos", "  Como sistema de gestion\r\n  Quiero poder crear leer actualizar y eliminar produc" +
                "tos\r\n  Para mantener el inventario actualizado", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ProductIntegration.feature"
#line hidden
        
        public IntegracionCRUDDeProductosFeature(IntegracionCRUDDeProductosFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
  await testRunner.GivenAsync("la base de datos esta limpia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
  await testRunner.AndAsync("existe una categoria \"Alimentos\" con id 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PR-01 - Crear producto completo - Happy Path 1")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Productos")]
        [Xunit.TraitAttribute("Description", "PR-01 - Crear producto completo - Happy Path 1")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "product")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task PR_01_CrearProductoCompleto_HappyPath1()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "product",
                    "create",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PR-01 - Crear producto completo - Happy Path 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table12.AddRow(new string[] {
                            "Name",
                            "Quinua Organica"});
                table12.AddRow(new string[] {
                            "Description",
                            "Quinua de Bolivia"});
                table12.AddRow(new string[] {
                            "Brand",
                            "Bolivia Natural"});
                table12.AddRow(new string[] {
                            "Price",
                            "28.50"});
                table12.AddRow(new string[] {
                            "Stock",
                            "100"});
                table12.AddRow(new string[] {
                            "CategoryId",
                            "1"});
#line 16
  await testRunner.WhenAsync("creo un producto con los siguientes datos:", ((string)(null)), table12, "When ");
#line hidden
#line 24
  await testRunner.ThenAsync("el producto debe crearse exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
  await testRunner.AndAsync("debe tener Stock 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
  await testRunner.AndAsync("debe estar asociado a la categoria 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PR-02 - Crear producto con descripcion vacia - Happy Path 2")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Productos")]
        [Xunit.TraitAttribute("Description", "PR-02 - Crear producto con descripcion vacia - Happy Path 2")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "product")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task PR_02_CrearProductoConDescripcionVacia_HappyPath2()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "product",
                    "create",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PR-02 - Crear producto con descripcion vacia - Happy Path 2", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table13.AddRow(new string[] {
                            "Name",
                            "Arroz Premium 1kg"});
                table13.AddRow(new string[] {
                            "Description",
                            ""});
                table13.AddRow(new string[] {
                            "Brand",
                            "Del Campo"});
                table13.AddRow(new string[] {
                            "Price",
                            "12.50"});
                table13.AddRow(new string[] {
                            "Stock",
                            "200"});
                table13.AddRow(new string[] {
                            "CategoryId",
                            "1"});
#line 30
  await testRunner.WhenAsync("creo un producto con los siguientes datos:", ((string)(null)), table13, "When ");
#line hidden
#line 38
  await testRunner.ThenAsync("el producto debe crearse exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
  await testRunner.AndAsync("debe tener Stock 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PR-03 - Crear producto con precio negativo - Unhappy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Productos")]
        [Xunit.TraitAttribute("Description", "PR-03 - Crear producto con precio negativo - Unhappy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "product")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "unhappy")]
        public async System.Threading.Tasks.Task PR_03_CrearProductoConPrecioNegativo_UnhappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "product",
                    "create",
                    "unhappy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PR-03 - Crear producto con precio negativo - Unhappy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 43
  await testRunner.WhenAsync("intento crear un producto con precio -10.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
  await testRunner.ThenAsync("la creacion debe fallar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
  await testRunner.AndAsync("debe mostrar error de validacion de precio", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PR-04 - Actualizar precio y stock - Happy Path 1")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Productos")]
        [Xunit.TraitAttribute("Description", "PR-04 - Actualizar precio y stock - Happy Path 1")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "product")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task PR_04_ActualizarPrecioYStock_HappyPath1()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "product",
                    "update",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PR-04 - Actualizar precio y stock - Happy Path 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 53
  await testRunner.GivenAsync("existe un producto \"Azucar Refinada\" con precio 8.50 y stock 50", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table14.AddRow(new string[] {
                            "Price",
                            "9.00"});
                table14.AddRow(new string[] {
                            "Stock",
                            "75"});
#line 54
  await testRunner.WhenAsync("actualizo el producto con:", ((string)(null)), table14, "When ");
#line hidden
#line 58
  await testRunner.ThenAsync("la actualizacion debe ser exitosa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
  await testRunner.AndAsync("el precio debe ser 9.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
  await testRunner.AndAsync("el stock debe ser 75", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PR-05 - Actualizar manteniendo mismo nombre - Happy Path 2")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Productos")]
        [Xunit.TraitAttribute("Description", "PR-05 - Actualizar manteniendo mismo nombre - Happy Path 2")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "product")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task PR_05_ActualizarManteniendoMismoNombre_HappyPath2()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "product",
                    "update",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PR-05 - Actualizar manteniendo mismo nombre - Happy Path 2", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 64
  await testRunner.GivenAsync("existe un producto \"Sal Fina 1kg\" con precio 3.50 y stock 80", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table15.AddRow(new string[] {
                            "Name",
                            "Sal Fina 1kg"});
                table15.AddRow(new string[] {
                            "Description",
                            "Sal refinada"});
                table15.AddRow(new string[] {
                            "Price",
                            "4.00"});
#line 65
  await testRunner.WhenAsync("actualizo el producto con:", ((string)(null)), table15, "When ");
#line hidden
#line 70
  await testRunner.ThenAsync("la actualizacion debe ser exitosa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
  await testRunner.AndAsync("los nuevos datos deben estar guardados", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PR-06 - Actualizar con stock negativo - Unhappy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Productos")]
        [Xunit.TraitAttribute("Description", "PR-06 - Actualizar con stock negativo - Unhappy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "product")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "unhappy")]
        public async System.Threading.Tasks.Task PR_06_ActualizarConStockNegativo_UnhappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "product",
                    "update",
                    "unhappy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PR-06 - Actualizar con stock negativo - Unhappy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 74
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 75
  await testRunner.GivenAsync("existe un producto \"Aceite Vegetal\" con stock 30", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
  await testRunner.WhenAsync("intento actualizar el stock a -5", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
  await testRunner.ThenAsync("la actualizacion debe fallar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 78
  await testRunner.AndAsync("debe mostrar error de validacion de stock", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PR-07 - Eliminar producto - Happy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Productos")]
        [Xunit.TraitAttribute("Description", "PR-07 - Eliminar producto - Happy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "product")]
        [Xunit.TraitAttribute("Category", "delete")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task PR_07_EliminarProducto_HappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "product",
                    "delete",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PR-07 - Eliminar producto - Happy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 86
  await testRunner.GivenAsync("existe un producto \"Producto Temporal\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 87
  await testRunner.WhenAsync("elimino el producto", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
  await testRunner.ThenAsync("el Status del producto debe cambiar a 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 89
  await testRunner.AndAsync("el producto no debe aparecer en busquedas activas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PR-08 - Buscar productos por categoria - Happy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion CRUD de Productos")]
        [Xunit.TraitAttribute("Description", "PR-08 - Buscar productos por categoria - Happy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "product")]
        [Xunit.TraitAttribute("Category", "read")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task PR_08_BuscarProductosPorCategoria_HappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "product",
                    "read",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PR-08 - Buscar productos por categoria - Happy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 96
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Price",
                            "Stock"});
                table16.AddRow(new string[] {
                            "Arroz",
                            "10.00",
                            "50"});
                table16.AddRow(new string[] {
                            "Azucar",
                            "8.00",
                            "60"});
                table16.AddRow(new string[] {
                            "Sal",
                            "3.50",
                            "100"});
#line 97
  await testRunner.GivenAsync("existen los siguientes productos activos en categoria 1:", ((string)(null)), table16, "Given ");
#line hidden
#line 102
  await testRunner.WhenAsync("busco productos de la categoria 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 103
  await testRunner.ThenAsync("debo recibir 3 productos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 104
  await testRunner.AndAsync("todos deben tener Status 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await IntegracionCRUDDeProductosFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await IntegracionCRUDDeProductosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
