// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PruebasBBD.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class IntegracionDelProcesoPrincipalDeVentasFeature : object, Xunit.IClassFixture<IntegracionDelProcesoPrincipalDeVentasFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Integracion del Proceso Principal de Ventas", "  Como sistema de gestion\r\n  Quiero procesar ventas completas\r\n  Para actualizar " +
                "inventario y registrar transacciones correctamente", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SalesIntegration.feature"
#line hidden
        
        public IntegracionDelProcesoPrincipalDeVentasFeature(IntegracionDelProcesoPrincipalDeVentasFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
  await testRunner.GivenAsync("la base de datos esta limpia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
  await testRunner.AndAsync("existe una categoria \"Alimentos\" con id 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "Price",
                        "Stock",
                        "CategoryId"});
            table17.AddRow(new string[] {
                        "Quinua Premium",
                        "28.50",
                        "100",
                        "1"});
            table17.AddRow(new string[] {
                        "Arroz Integral",
                        "15.00",
                        "80",
                        "1"});
            table17.AddRow(new string[] {
                        "Aceite Vegetal",
                        "12.00",
                        "50",
                        "1"});
#line 9
  await testRunner.AndAsync("existen los siguientes productos:", ((string)(null)), table17, "And ");
#line hidden
#line 14
  await testRunner.AndAsync("existe un cliente \"Juan Perez\" con TaxDocument \"12345678\" para ventas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="VT-01 - Procesar venta completa con multiples productos - Happy Path")]
        [Xunit.TraitAttribute("FeatureTitle", "Integracion del Proceso Principal de Ventas")]
        [Xunit.TraitAttribute("Description", "VT-01 - Procesar venta completa con multiples productos - Happy Path")]
        [Xunit.TraitAttribute("Category", "integration")]
        [Xunit.TraitAttribute("Category", "sales")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "happy")]
        public async System.Threading.Tasks.Task VT_01_ProcesarVentaCompletaConMultiplesProductos_HappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "sales",
                    "process",
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VT-01 - Procesar venta completa con multiples productos - Happy Path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "ProductName",
                            "Quantity"});
                table18.AddRow(new string[] {
                            "Quinua Premium",
                            "3"});
                table18.AddRow(new string[] {
                            "Arroz Integral",
                            "5"});
                table18.AddRow(new string[] {
                            "Aceite Vegetal",
                            "2"});
#line 22
  await testRunner.GivenAsync("tengo los siguientes productos en el carrito:", ((string)(null)), table18, "Given ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table19.AddRow(new string[] {
                            "ClientId",
                            "1"});
                table19.AddRow(new string[] {
                            "PaymentType",
                            "Efectivo"});
                table19.AddRow(new string[] {
                            "CashReceived",
                            "200.00"});
#line 27
  await testRunner.WhenAsync("proceso la venta con los siguientes datos:", ((string)(null)), table19, "When ");
#line hidden
#line 32
  await testRunner.ThenAsync("la venta debe registrarse exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
  await testRunner.AndAsync("el total debe ser 184.50", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
  await testRunner.AndAsync("el cambio debe ser 15.50", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
  await testRunner.AndAsync("el stock de \"Quinua Premium\" debe ser 97", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
  await testRunner.AndAsync("el stock de \"Arroz Integral\" debe ser 75", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
  await testRunner.AndAsync("el stock de \"Aceite Vegetal\" debe ser 48", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
  await testRunner.AndAsync("debe existir 1 registro en Sales", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
  await testRunner.AndAsync("deben existir 3 registros en SaleItems", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
  await testRunner.AndAsync("la fecha de venta debe ser la actual", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await IntegracionDelProcesoPrincipalDeVentasFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await IntegracionDelProcesoPrincipalDeVentasFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
