// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PruebasUIBased.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CRUDDeCategorias_UITestingFeature : object, global::Xunit.IClassFixture<CRUDDeCategorias_UITestingFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "CRUD de Categorias - UI Testing", "Como usuario del sistema\r\nQuiero gestionar categorias\r\nPara organizar los product" +
                "os", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CategoryCRUD.feature"
#line hidden
        
        public CRUDDeCategorias_UITestingFeature(CRUDDeCategorias_UITestingFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
  await testRunner.GivenAsync("que la aplicacion esta en ejecucion", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
  await testRunner.AndAsync("navego a la pagina de categorias", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CategoryCRUD.feature.ndjson", 11);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="CC-01 - Crear categoria con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing")]
        [global::Xunit.TraitAttribute("Description", "CC-01 - Crear categoria con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "create")]
        [global::Xunit.TraitAttribute("Category", "pairwise")]
        [global::Xunit.InlineDataAttribute("Cat Valida 1", "Descripcion valida normal", "debo ver mensaje de exito en categoria", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("Cat Valida 2", "", "debo ver mensaje de exito en categoria", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("Cat Muy Larga Nombre", "Descripcion con 255 caracteres max", "debo ver mensaje de exito en categoria", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("", "Descripcion sin nombre", "debo ver error de validacion en categoria", "3", new string[0])]
        public async global::System.Threading.Tasks.Task CC_01_CrearCategoriaConCombinacionesPairwise(string nombre, string descripcion, string resultado, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "category",
                    "create",
                    "pairwise"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Nombre", nombre);
            argumentsOfScenario.Add("Descripcion", descripcion);
            argumentsOfScenario.Add("Resultado", resultado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CC-01 - Crear categoria con combinaciones Pairwise", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 12
  await testRunner.WhenAsync("hago clic en agregar nueva categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
  await testRunner.AndAsync(string.Format("lleno el formulario de categoria con nombre \"{0}\" y descripcion \"{1}\"", nombre, descripcion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
  await testRunner.AndAsync("hago clic en guardar categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
  await testRunner.ThenAsync(string.Format("{0}", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="CC-02 - Actualizar categoria con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing")]
        [global::Xunit.TraitAttribute("Description", "CC-02 - Actualizar categoria con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "update")]
        [global::Xunit.TraitAttribute("Category", "pairwise")]
        [global::Xunit.InlineDataAttribute("CatActualizada", "Nueva descripcion valida", "debo ver mensaje de exito en categoria", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("CatModificada", "Descripcion modificada", "debo ver mensaje de exito en categoria", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("NombreNuevo", "", "debo ver mensaje de exito en categoria", "6", new string[0])]
        public async global::System.Threading.Tasks.Task CC_02_ActualizarCategoriaConCombinacionesPairwise(string nuevoNombre, string nuevaDescripcion, string resultado, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "category",
                    "update",
                    "pairwise"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("NuevoNombre", nuevoNombre);
            argumentsOfScenario.Add("NuevaDescripcion", nuevaDescripcion);
            argumentsOfScenario.Add("Resultado", resultado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CC-02 - Actualizar categoria con combinaciones Pairwise", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 26
  await testRunner.GivenAsync("existe una categoria creada con nombre \"CatBase\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
  await testRunner.WhenAsync("hago clic en editar categoria \"CatBase\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
  await testRunner.AndAsync(string.Format("actualizo el formulario con nombre \"{0}\" y descripcion \"{1}\"", nuevoNombre, nuevaDescripcion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
  await testRunner.AndAsync("hago clic en guardar categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
  await testRunner.ThenAsync(string.Format("{0}", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="CC-03 - Eliminar categoria")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing")]
        [global::Xunit.TraitAttribute("Description", "CC-03 - Eliminar categoria")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "delete")]
        [global::Xunit.TraitAttribute("Category", "happy")]
        public async global::System.Threading.Tasks.Task CC_03_EliminarCategoria()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "category",
                    "delete",
                    "happy"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CC-03 - Eliminar categoria", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 40
  await testRunner.GivenAsync("existe una categoria creada con nombre \"CategoriaParaEliminar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
  await testRunner.WhenAsync("hago clic en eliminar categoria \"CategoriaParaEliminar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
  await testRunner.ThenAsync("la categoria \"CategoriaParaEliminar\" no debe aparecer en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="CC-04 - Listar categorias activas")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing")]
        [global::Xunit.TraitAttribute("Description", "CC-04 - Listar categorias activas")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "read")]
        [global::Xunit.TraitAttribute("Category", "happy")]
        public async global::System.Threading.Tasks.Task CC_04_ListarCategoriasActivas()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "category",
                    "read",
                    "happy"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CC-04 - Listar categorias activas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Nombre"});
                table1.AddRow(new string[] {
                            "Categoria A"});
                table1.AddRow(new string[] {
                            "Categoria B"});
                table1.AddRow(new string[] {
                            "Categoria C"});
#line 46
  await testRunner.GivenAsync("existen las siguientes categorias en el sistema:", ((string)(null)), table1, "Given ");
#line hidden
#line 51
  await testRunner.WhenAsync("navego a la pagina de categorias", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
  await testRunner.ThenAsync("debo ver al menos 3 categorias en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CRUDDeCategorias_UITestingFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CRUDDeCategorias_UITestingFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
