// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PruebasUIBased.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CRUDDeCategorias_UITestingConPairwiseFeature : object, global::Xunit.IClassFixture<CRUDDeCategorias_UITestingConPairwiseFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "CRUD de Categorias - UI Testing con Pairwise", "Como usuario del sistema\r\nQuiero gestionar categorias\r\nPara organizar los product" +
                "os", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CategoryCRUD.feature"
#line hidden
        
        public CRUDDeCategorias_UITestingConPairwiseFeature(CRUDDeCategorias_UITestingConPairwiseFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
  await testRunner.GivenAsync("que la aplicacion esta en ejecucion", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
  await testRunner.AndAsync("navego a la pagina de categorias", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CategoryCRUD.feature.ndjson", 18);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="PW-CAT-01 - Crear categoria con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing con Pairwise")]
        [global::Xunit.TraitAttribute("Description", "PW-CAT-01 - Crear categoria con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "create")]
        [global::Xunit.TraitAttribute("Category", "pairwise")]
        [global::Xunit.TraitAttribute("Category", "pw-cat-01")]
        [global::Xunit.InlineDataAttribute("PW01", "CatPairwise01", "Descripcion valida normal", "debo ver mensaje de exito en categoria", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("PW02", "CatPairwise02", "", "debo ver mensaje de exito en categoria", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("PW03", "CatDescLarga03", "Esta es una descripcion muy larga que tiene muchos caracteres", "debo ver mensaje de exito en categoria", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("PW04", "", "Descripcion sin nombre categoria", "debo ver error de validacion en categoria", "3", new string[0])]
        public async global::System.Threading.Tasks.Task PW_CAT_01_CrearCategoriaConCombinacionesPairwise(string testID, string nombre, string descripcion, string resultado, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "category",
                    "create",
                    "pairwise",
                    "pw-cat-01"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("TestID", testID);
            argumentsOfScenario.Add("Nombre", nombre);
            argumentsOfScenario.Add("Descripcion", descripcion);
            argumentsOfScenario.Add("Resultado", resultado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PW-CAT-01 - Crear categoria con combinaciones Pairwise", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 12
  await testRunner.WhenAsync("hago clic en agregar nueva categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
  await testRunner.AndAsync(string.Format("lleno el formulario de categoria con nombre \"{0}\" y descripcion \"{1}\"", nombre, descripcion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
  await testRunner.AndAsync("hago clic en guardar categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
  await testRunner.ThenAsync(string.Format("{0}", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="PW-CAT-02 - Actualizar categoria con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing con Pairwise")]
        [global::Xunit.TraitAttribute("Description", "PW-CAT-02 - Actualizar categoria con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "update")]
        [global::Xunit.TraitAttribute("Category", "pairwise")]
        [global::Xunit.TraitAttribute("Category", "pw-cat-02")]
        [global::Xunit.InlineDataAttribute("PW05", "CatActualizada05", "Nueva descripcion valida actualizada", "debo ver mensaje de exito en categoria", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("PW06", "CatBaseUpdate", "Mismo nombre diferente descripcion", "debo ver mensaje de exito en categoria", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("PW07", "CatModificada07", "", "debo ver mensaje de exito en categoria", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("PW08", "CatDescLargaUpd08", "Descripcion actualizada muy extensa para validar", "debo ver mensaje de exito en categoria", "7", new string[0])]
        public async global::System.Threading.Tasks.Task PW_CAT_02_ActualizarCategoriaConCombinacionesPairwise(string testID, string nuevoNombre, string nuevaDescripcion, string resultado, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "category",
                    "update",
                    "pairwise",
                    "pw-cat-02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("TestID", testID);
            argumentsOfScenario.Add("NuevoNombre", nuevoNombre);
            argumentsOfScenario.Add("NuevaDescripcion", nuevaDescripcion);
            argumentsOfScenario.Add("Resultado", resultado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PW-CAT-02 - Actualizar categoria con combinaciones Pairwise", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 26
  await testRunner.GivenAsync("existe una categoria creada con nombre \"CatBaseUpdate\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
  await testRunner.WhenAsync("hago clic en editar categoria \"CatBaseUpdate\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
  await testRunner.AndAsync(string.Format("actualizo el formulario con nombre \"{0}\" y descripcion \"{1}\"", nuevoNombre, nuevaDescripcion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
  await testRunner.AndAsync("hago clic en guardar categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
  await testRunner.ThenAsync(string.Format("{0}", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BVA-CAT-01 - Crear categoria con nombre de 1 caracter (minimo)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing con Pairwise")]
        [global::Xunit.TraitAttribute("Description", "BVA-CAT-01 - Crear categoria con nombre de 1 caracter (minimo)")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "bva")]
        [global::Xunit.TraitAttribute("Category", "bva-cat-01")]
        public async global::System.Threading.Tasks.Task BVA_CAT_01_CrearCategoriaConNombreDe1CaracterMinimo()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "category",
                    "bva",
                    "bva-cat-01"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BVA-CAT-01 - Crear categoria con nombre de 1 caracter (minimo)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 41
  await testRunner.WhenAsync("hago clic en agregar nueva categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
  await testRunner.AndAsync("lleno el formulario de categoria con nombre \"A\" y descripcion \"Categoria con nomb" +
                        "re minimo\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
  await testRunner.AndAsync("hago clic en guardar categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
  await testRunner.ThenAsync("debo ver mensaje de exito en categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BVA-CAT-02 - Crear categoria con nombre largo (Excede limite)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing con Pairwise")]
        [global::Xunit.TraitAttribute("Description", "BVA-CAT-02 - Crear categoria con nombre largo (Excede limite)")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "bva")]
        [global::Xunit.TraitAttribute("Category", "bva-cat-02")]
        public async global::System.Threading.Tasks.Task BVA_CAT_02_CrearCategoriaConNombreLargoExcedeLimite()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "category",
                    "bva",
                    "bva-cat-02"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BVA-CAT-02 - Crear categoria con nombre largo (Excede limite)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 48
  await testRunner.WhenAsync("hago clic en agregar nueva categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
  await testRunner.AndAsync("lleno el formulario de categoria con nombre \"CategoriaConNombreDeCincuentaCaracte" +
                        "resExac\" y descripcion \"Test de longitud\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
  await testRunner.AndAsync("hago clic en guardar categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
  await testRunner.ThenAsync("la creacion debe fallar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BVA-CAT-03 - Crear categoria con descripcion de 1 caracter (minimo)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing con Pairwise")]
        [global::Xunit.TraitAttribute("Description", "BVA-CAT-03 - Crear categoria con descripcion de 1 caracter (minimo)")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "bva")]
        [global::Xunit.TraitAttribute("Category", "bva-cat-03")]
        public async global::System.Threading.Tasks.Task BVA_CAT_03_CrearCategoriaConDescripcionDe1CaracterMinimo()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "category",
                    "bva",
                    "bva-cat-03"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BVA-CAT-03 - Crear categoria con descripcion de 1 caracter (minimo)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 55
  await testRunner.WhenAsync("hago clic en agregar nueva categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
  await testRunner.AndAsync("lleno el formulario de categoria con nombre \"CatDescMinBVA\" y descripcion \"D\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
  await testRunner.AndAsync("hago clic en guardar categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
  await testRunner.ThenAsync("debo ver mensaje de exito en categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BVA-CAT-04 - Crear categoria con descripcion de 255 caracteres (maximo)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing con Pairwise")]
        [global::Xunit.TraitAttribute("Description", "BVA-CAT-04 - Crear categoria con descripcion de 255 caracteres (maximo)")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "bva")]
        [global::Xunit.TraitAttribute("Category", "bva-cat-04")]
        public async global::System.Threading.Tasks.Task BVA_CAT_04_CrearCategoriaConDescripcionDe255CaracteresMaximo()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "category",
                    "bva",
                    "bva-cat-04"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BVA-CAT-04 - Crear categoria con descripcion de 255 caracteres (maximo)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 62
  await testRunner.WhenAsync("hago clic en agregar nueva categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
  await testRunner.AndAsync(@"lleno el formulario de categoria con nombre ""CatDescMaxBVA"" y descripcion ""Esta descripcion tiene exactamente doscientos cincuenta y cinco caracteres para probar el limite maximo permitido en el campo de descripcion de categoria del sistema MicroMercado que estamos probando ahora mismo con pruebas automatizadas de Reqnroll""", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
  await testRunner.AndAsync("hago clic en guardar categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
  await testRunner.ThenAsync("la creacion debe fallar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="PE-CAT-01 - Crear categoria con nombre duplicado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing con Pairwise")]
        [global::Xunit.TraitAttribute("Description", "PE-CAT-01 - Crear categoria con nombre duplicado")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "pe")]
        [global::Xunit.TraitAttribute("Category", "pe-cat-01")]
        public async global::System.Threading.Tasks.Task PE_CAT_01_CrearCategoriaConNombreDuplicado()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "category",
                    "pe",
                    "pe-cat-01"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PE-CAT-01 - Crear categoria con nombre duplicado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 69
  await testRunner.GivenAsync("existe una categoria creada con nombre \"CatDuplicadaPE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
  await testRunner.WhenAsync("hago clic en agregar nueva categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
  await testRunner.AndAsync("lleno el formulario de categoria con nombre \"CatDuplicadaPE\" y descripcion \"Inten" +
                        "tando duplicar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
  await testRunner.AndAsync("hago clic en guardar categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
  await testRunner.ThenAsync("debo ver error de validacion en categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="PE-CAT-02 - Eliminar categoria existente (borrado logico)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing con Pairwise")]
        [global::Xunit.TraitAttribute("Description", "PE-CAT-02 - Eliminar categoria existente (borrado logico)")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "pe")]
        [global::Xunit.TraitAttribute("Category", "pe-cat-02")]
        public async global::System.Threading.Tasks.Task PE_CAT_02_EliminarCategoriaExistenteBorradoLogico()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "category",
                    "pe",
                    "pe-cat-02"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PE-CAT-02 - Eliminar categoria existente (borrado logico)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 76
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 77
  await testRunner.GivenAsync("existe una categoria creada con nombre \"CatParaEliminarPE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
  await testRunner.WhenAsync("hago clic en eliminar categoria \"CatParaEliminarPE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
  await testRunner.ThenAsync("la categoria \"CatParaEliminarPE\" no debe aparecer en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="PE-CAT-03 - Listar categorias activas")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing con Pairwise")]
        [global::Xunit.TraitAttribute("Description", "PE-CAT-03 - Listar categorias activas")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "pe")]
        [global::Xunit.TraitAttribute("Category", "pe-cat-03")]
        public async global::System.Threading.Tasks.Task PE_CAT_03_ListarCategoriasActivas()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "category",
                    "pe",
                    "pe-cat-03"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PE-CAT-03 - Listar categorias activas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Nombre"});
                table1.AddRow(new string[] {
                            "CatListadoA"});
                table1.AddRow(new string[] {
                            "CatListadoB"});
                table1.AddRow(new string[] {
                            "CatListadoC"});
#line 83
  await testRunner.GivenAsync("existen las siguientes categorias en el sistema:", ((string)(null)), table1, "Given ");
#line hidden
#line 88
  await testRunner.WhenAsync("navego a la pagina de categorias", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
  await testRunner.ThenAsync("debo ver al menos 3 categorias en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="PE-CAT-04 - Actualizar categoria manteniendo nombre unico propio")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Categorias - UI Testing con Pairwise")]
        [global::Xunit.TraitAttribute("Description", "PE-CAT-04 - Actualizar categoria manteniendo nombre unico propio")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "category")]
        [global::Xunit.TraitAttribute("Category", "pe")]
        [global::Xunit.TraitAttribute("Category", "pe-cat-04")]
        public async global::System.Threading.Tasks.Task PE_CAT_04_ActualizarCategoriaManteniendoNombreUnicoPropio()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "category",
                    "pe",
                    "pe-cat-04"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PE-CAT-04 - Actualizar categoria manteniendo nombre unico propio", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 92
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 93
  await testRunner.GivenAsync("existe una categoria creada con nombre \"CatMismoNombrePE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 94
  await testRunner.WhenAsync("hago clic en editar categoria \"CatMismoNombrePE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 95
  await testRunner.AndAsync("actualizo el formulario con nombre \"CatMismoNombrePE\" y descripcion \"Solo cambio " +
                        "descripcion no nombre\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
  await testRunner.AndAsync("hago clic en guardar categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
  await testRunner.ThenAsync("debo ver mensaje de exito en categoria", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CRUDDeCategorias_UITestingConPairwiseFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CRUDDeCategorias_UITestingConPairwiseFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
