// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PruebasUIBased.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CRUDDeProductos_UITestingFeature : object, global::Xunit.IClassFixture<CRUDDeProductos_UITestingFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "CRUD de Productos - UI Testing", "Como usuario del sistema\r\nQuiero gestionar productos\r\nPara mantener el inventario" +
                " actualizado", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ProductCRUD.feature"
#line hidden
        
        public CRUDDeProductos_UITestingFeature(CRUDDeProductos_UITestingFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
  await testRunner.GivenAsync("que la aplicacion esta en ejecucion", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
  await testRunner.AndAsync("navego a la pagina de productos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
  await testRunner.AndAsync("existe una categoria \"Alimentos\" para productos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ProductCRUD.feature.ndjson", 11);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="CP-01 - Crear producto con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Productos - UI Testing")]
        [global::Xunit.TraitAttribute("Description", "CP-01 - Crear producto con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "product")]
        [global::Xunit.TraitAttribute("Category", "create")]
        [global::Xunit.TraitAttribute("Category", "pairwise")]
        [global::Xunit.InlineDataAttribute("Producto Valid 1", "Desc valida", "MarcaA", "10.50", "100", "debo ver mensaje de exito en producto", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("Producto Valid 2", "", "MarcaB", "5.00", "1", "debo ver mensaje de exito en producto", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("Producto Valid 3", "Desc muy larga", "MarcaC", "999.99", "9999", "debo ver mensaje de exito en producto", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("", "Desc sin nombre", "MarcaSinNom", "10.00", "50", "debo ver error de validacion en producto", "3", new string[0])]
        public async global::System.Threading.Tasks.Task CP_01_CrearProductoConCombinacionesPairwise(string nombre, string descripcion, string marca, string precio, string stock, string resultado, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "product",
                    "create",
                    "pairwise"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Nombre", nombre);
            argumentsOfScenario.Add("Descripcion", descripcion);
            argumentsOfScenario.Add("Marca", marca);
            argumentsOfScenario.Add("Precio", precio);
            argumentsOfScenario.Add("Stock", stock);
            argumentsOfScenario.Add("Resultado", resultado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CP-01 - Crear producto con combinaciones Pairwise", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 13
  await testRunner.WhenAsync("hago clic en agregar nuevo producto", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table5.AddRow(new string[] {
                            "Nombre",
                            string.Format("{0}", nombre)});
                table5.AddRow(new string[] {
                            "Descripcion",
                            string.Format("{0}", descripcion)});
                table5.AddRow(new string[] {
                            "Marca",
                            string.Format("{0}", marca)});
                table5.AddRow(new string[] {
                            "Precio",
                            string.Format("{0}", precio)});
                table5.AddRow(new string[] {
                            "Stock",
                            string.Format("{0}", stock)});
                table5.AddRow(new string[] {
                            "Categoria",
                            "1"});
#line 14
  await testRunner.AndAsync("lleno el formulario de producto con los siguientes datos:", ((string)(null)), table5, "And ");
#line hidden
#line 22
  await testRunner.AndAsync("hago clic en guardar producto", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
  await testRunner.ThenAsync(string.Format("{0}", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="CP-02 - Actualizar producto con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Productos - UI Testing")]
        [global::Xunit.TraitAttribute("Description", "CP-02 - Actualizar producto con combinaciones Pairwise")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "product")]
        [global::Xunit.TraitAttribute("Category", "update")]
        [global::Xunit.TraitAttribute("Category", "pairwise")]
        [global::Xunit.InlineDataAttribute("ProductoActualizado", "Desc actualizada", "15.00", "200", "debo ver mensaje de exito en producto", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("ProductoParaActualizar", "Nueva desc", "20.00", "150", "debo ver mensaje de exito en producto", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("ProductoNuevoPrecio", "", "25.50", "1", "debo ver mensaje de exito en producto", "6", new string[0])]
        public async global::System.Threading.Tasks.Task CP_02_ActualizarProductoConCombinacionesPairwise(string nuevoNombre, string nuevaDescripcion, string nuevoPrecio, string nuevoStock, string resultado, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "product",
                    "update",
                    "pairwise"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("NuevoNombre", nuevoNombre);
            argumentsOfScenario.Add("NuevaDescripcion", nuevaDescripcion);
            argumentsOfScenario.Add("NuevoPrecio", nuevoPrecio);
            argumentsOfScenario.Add("NuevoStock", nuevoStock);
            argumentsOfScenario.Add("Resultado", resultado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CP-02 - Actualizar producto con combinaciones Pairwise", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 34
  await testRunner.GivenAsync("existe un producto creado con nombre \"ProductoParaActualizar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
  await testRunner.WhenAsync("hago clic en editar producto \"ProductoParaActualizar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table6.AddRow(new string[] {
                            "Nombre",
                            string.Format("{0}", nuevoNombre)});
                table6.AddRow(new string[] {
                            "Descripcion",
                            string.Format("{0}", nuevaDescripcion)});
                table6.AddRow(new string[] {
                            "Precio",
                            string.Format("{0}", nuevoPrecio)});
                table6.AddRow(new string[] {
                            "Stock",
                            string.Format("{0}", nuevoStock)});
#line 36
  await testRunner.AndAsync("actualizo el formulario de producto con:", ((string)(null)), table6, "And ");
#line hidden
#line 42
  await testRunner.AndAsync("hago clic en guardar producto", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
  await testRunner.ThenAsync(string.Format("{0}", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="CP-03 - Eliminar producto")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Productos - UI Testing")]
        [global::Xunit.TraitAttribute("Description", "CP-03 - Eliminar producto")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "product")]
        [global::Xunit.TraitAttribute("Category", "delete")]
        [global::Xunit.TraitAttribute("Category", "happy")]
        public async global::System.Threading.Tasks.Task CP_03_EliminarProducto()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "product",
                    "delete",
                    "happy"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CP-03 - Eliminar producto", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 53
  await testRunner.GivenAsync("existe un producto creado con nombre \"ProductoParaEliminar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
  await testRunner.WhenAsync("hago clic en eliminar producto \"ProductoParaEliminar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
  await testRunner.ThenAsync("el producto \"ProductoParaEliminar\" no debe aparecer en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="CP-04 - Listar productos activos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "CRUD de Productos - UI Testing")]
        [global::Xunit.TraitAttribute("Description", "CP-04 - Listar productos activos")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "product")]
        [global::Xunit.TraitAttribute("Category", "read")]
        [global::Xunit.TraitAttribute("Category", "happy")]
        public async global::System.Threading.Tasks.Task CP_04_ListarProductosActivos()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "product",
                    "read",
                    "happy"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CP-04 - Listar productos activos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Nombre"});
                table7.AddRow(new string[] {
                            "Producto A"});
                table7.AddRow(new string[] {
                            "Producto B"});
                table7.AddRow(new string[] {
                            "Producto C"});
#line 59
  await testRunner.GivenAsync("existen los siguientes productos en el sistema:", ((string)(null)), table7, "Given ");
#line hidden
#line 64
  await testRunner.WhenAsync("navego a la pagina de productos", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
  await testRunner.ThenAsync("debo ver al menos 3 productos en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CRUDDeProductos_UITestingFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CRUDDeProductos_UITestingFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
